default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("POSTGRES_HOSTNAME", "localhost") %>
  username: #set your username here
  password: #set your password here

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE", "weather_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE", "weather_test") %>

production:
  url: <%= ENV.fetch('DATABASE_URL', '') %>
